-- MySQL Script generated by MySQL Workbench
-- mer. 22 mai 2019 17:03:36 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema assolaface
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assolaface
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assolaface` DEFAULT CHARACTER SET utf8 ;
USE `assolaface` ;

-- -----------------------------------------------------
-- Table `assolaface`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `loginUtilisateur` VARCHAR(45) NOT NULL,
  `passwordUtilisateur` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assolaface`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`evenement` (
  `idEvenement` INT NOT NULL,
  `nomEvenement` VARCHAR(100) NOT NULL,
  `dateEvenement` DATETIME NOT NULL,
  `lieuEvenement` VARCHAR(100) NOT NULL,
  `prixEntreeEvenement` FLOAT NOT NULL,
  `descriptionEvenement` TEXT(300) NOT NULL,
  PRIMARY KEY (`idEvenement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assolaface`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`entreprise` (
  `idEntreprise` INT NOT NULL,
  `nomEntreprise` VARCHAR(100) NOT NULL,
  `domaineEntreprise` VARCHAR(100) NOT NULL,
  `descriptionEntreprise` TEXT(200) NOT NULL,
  `cheminLogoEntreprise` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idEntreprise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assolaface`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`photo` (
  `idPhoto` INT NOT NULL,
  `cheminPhoto` VARCHAR(200) NOT NULL,
  `entreprise_idEntreprise` INT NOT NULL,
  PRIMARY KEY (`idPhoto`),
  INDEX `fk_photo_entreprise1_idx` (`entreprise_idEntreprise` ASC),
  CONSTRAINT `fk_photo_entreprise1`
    FOREIGN KEY (`entreprise_idEntreprise`)
    REFERENCES `assolaface`.`entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assolaface`.`adherent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`adherent` (
  `idAdherent` INT NOT NULL,
  `nomAdherent` VARCHAR(60) NOT NULL,
  `prenomAdherent` VARCHAR(60) NOT NULL,
  `photo_idPhoto` INT NOT NULL,
  PRIMARY KEY (`idAdherent`, `photo_idPhoto`),
  INDEX `fk_adherent_photo_idx` (`photo_idPhoto` ASC),
  CONSTRAINT `fk_adherent_photo`
    FOREIGN KEY (`photo_idPhoto`)
    REFERENCES `assolaface`.`photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assolaface`.`coordonnees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`coordonnees` (
  `idCoordonnees` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  `tel` VARCHAR(14) NULL,
  `addresse` VARCHAR(200) NULL,
  `profilFacebook` VARCHAR(200) NULL,
  `profilInstagram` VARCHAR(200) NULL,
  `profilTwitter` VARCHAR(200) NULL,
  `urlSite` VARCHAR(300) NULL,
  `entreprise_idEntreprise` INT NOT NULL,
  `adherent_idAdherent` INT NOT NULL,
  `adherent_photo_idPhoto` INT NOT NULL,
  PRIMARY KEY (`idCoordonnees`),
  INDEX `fk_coordonnees_entreprise1_idx` (`entreprise_idEntreprise` ASC),
  INDEX `fk_coordonnees_adherent1_idx` (`adherent_idAdherent` ASC, `adherent_photo_idPhoto` ASC),
  CONSTRAINT `fk_coordonnees_entreprise1`
    FOREIGN KEY (`entreprise_idEntreprise`)
    REFERENCES `assolaface`.`entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordonnees_adherent1`
    FOREIGN KEY (`adherent_idAdherent` , `adherent_photo_idPhoto`)
    REFERENCES `assolaface`.`adherent` (`idAdherent` , `photo_idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assolaface`.`entreprise_gere_adherent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assolaface`.`entreprise_gere_adherent` (
  `entreprise_idEntreprise` INT NOT NULL,
  `adherent_idAdherent` INT NOT NULL,
  `adherent_photo_idPhoto` INT NOT NULL,
  PRIMARY KEY (`entreprise_idEntreprise`, `adherent_idAdherent`, `adherent_photo_idPhoto`),
  INDEX `fk_entreprise_has_adherent_adherent1_idx` (`adherent_idAdherent` ASC, `adherent_photo_idPhoto` ASC),
  INDEX `fk_entreprise_has_adherent_entreprise1_idx` (`entreprise_idEntreprise` ASC),
  CONSTRAINT `fk_entreprise_has_adherent_entreprise1`
    FOREIGN KEY (`entreprise_idEntreprise`)
    REFERENCES `assolaface`.`entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entreprise_has_adherent_adherent1`
    FOREIGN KEY (`adherent_idAdherent` , `adherent_photo_idPhoto`)
    REFERENCES `assolaface`.`adherent` (`idAdherent` , `photo_idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
